
lib_src_files += files('diagnostics.c', 'diagnostics.h', 'helper.c', 'helper.h', 'parser.c', 'parser.h', 'types.h'
, 'validate.c', 'validate.h')

install_headers(
    files('diagnostics.h', 'parser.h', 'types.h', 'validate.h'),
    install_dir: install_include_dir / 'parser',
    preserve_path: true,
)
